/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.fichaje.model.impl;

import aQute.bnd.annotation.ProviderType;

import es.vass.fichaje.model.Servicio;
import es.vass.fichaje.service.ServicioLocalServiceUtil;

/**
 * The extended model base implementation for the Servicio service. Represents a row in the &quot;Fichaje_Servicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServicioImpl
 * @see Servicio
 * @generated
 */
@ProviderType
public abstract class ServicioBaseImpl extends ServicioModelImpl
	implements Servicio {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a servicio model instance should use the {@link Servicio} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ServicioLocalServiceUtil.addServicio(this);
		}
		else {
			ServicioLocalServiceUtil.updateServicio(this);
		}
	}
}