/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.fichaje.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.asset.kernel.service.persistence.AssetEntryPersistence;
import com.liferay.asset.kernel.service.persistence.AssetTagPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import es.vass.fichaje.model.Fichaje;
import es.vass.fichaje.service.FichajeLocalService;
import es.vass.fichaje.service.persistence.FichajePersistence;
import es.vass.fichaje.service.persistence.ServicioPersistence;
import es.vass.fichaje.service.persistence.TipoServicioPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the fichaje local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link es.vass.fichaje.service.impl.FichajeLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see es.vass.fichaje.service.impl.FichajeLocalServiceImpl
 * @see es.vass.fichaje.service.FichajeLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class FichajeLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements FichajeLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link es.vass.fichaje.service.FichajeLocalServiceUtil} to access the fichaje local service.
	 */

	/**
	 * Adds the fichaje to the database. Also notifies the appropriate model listeners.
	 *
	 * @param fichaje the fichaje
	 * @return the fichaje that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Fichaje addFichaje(Fichaje fichaje) {
		fichaje.setNew(true);

		return fichajePersistence.update(fichaje);
	}

	/**
	 * Creates a new fichaje with the primary key. Does not add the fichaje to the database.
	 *
	 * @param fichajeId the primary key for the new fichaje
	 * @return the new fichaje
	 */
	@Override
	@Transactional(enabled = false)
	public Fichaje createFichaje(long fichajeId) {
		return fichajePersistence.create(fichajeId);
	}

	/**
	 * Deletes the fichaje with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param fichajeId the primary key of the fichaje
	 * @return the fichaje that was removed
	 * @throws PortalException if a fichaje with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Fichaje deleteFichaje(long fichajeId) throws PortalException {
		return fichajePersistence.remove(fichajeId);
	}

	/**
	 * Deletes the fichaje from the database. Also notifies the appropriate model listeners.
	 *
	 * @param fichaje the fichaje
	 * @return the fichaje that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Fichaje deleteFichaje(Fichaje fichaje) {
		return fichajePersistence.remove(fichaje);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Fichaje.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return fichajePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link es.vass.fichaje.model.impl.FichajeModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return fichajePersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link es.vass.fichaje.model.impl.FichajeModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return fichajePersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return fichajePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return fichajePersistence.countWithDynamicQuery(dynamicQuery, projection);
	}

	@Override
	public Fichaje fetchFichaje(long fichajeId) {
		return fichajePersistence.fetchByPrimaryKey(fichajeId);
	}

	/**
	 * Returns the fichaje with the matching UUID and company.
	 *
	 * @param uuid the fichaje's UUID
	 * @param companyId the primary key of the company
	 * @return the matching fichaje, or <code>null</code> if a matching fichaje could not be found
	 */
	@Override
	public Fichaje fetchFichajeByUuidAndCompanyId(String uuid, long companyId) {
		return fichajePersistence.fetchByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns the fichaje with the primary key.
	 *
	 * @param fichajeId the primary key of the fichaje
	 * @return the fichaje
	 * @throws PortalException if a fichaje with the primary key could not be found
	 */
	@Override
	public Fichaje getFichaje(long fichajeId) throws PortalException {
		return fichajePersistence.findByPrimaryKey(fichajeId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(fichajeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Fichaje.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("fichajeId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(fichajeLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Fichaje.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("fichajeId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(fichajeLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Fichaje.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("fichajeId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return fichajeLocalService.deleteFichaje((Fichaje)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return fichajePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the fichaje with the matching UUID and company.
	 *
	 * @param uuid the fichaje's UUID
	 * @param companyId the primary key of the company
	 * @return the matching fichaje
	 * @throws PortalException if a matching fichaje could not be found
	 */
	@Override
	public Fichaje getFichajeByUuidAndCompanyId(String uuid, long companyId)
		throws PortalException {
		return fichajePersistence.findByUuid_C_First(uuid, companyId, null);
	}

	/**
	 * Returns a range of all the fichajes.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link es.vass.fichaje.model.impl.FichajeModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of fichajes
	 * @param end the upper bound of the range of fichajes (not inclusive)
	 * @return the range of fichajes
	 */
	@Override
	public List<Fichaje> getFichajes(int start, int end) {
		return fichajePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of fichajes.
	 *
	 * @return the number of fichajes
	 */
	@Override
	public int getFichajesCount() {
		return fichajePersistence.countAll();
	}

	/**
	 * Updates the fichaje in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param fichaje the fichaje
	 * @return the fichaje that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Fichaje updateFichaje(Fichaje fichaje) {
		return fichajePersistence.update(fichaje);
	}

	/**
	 * Returns the fichaje local service.
	 *
	 * @return the fichaje local service
	 */
	public FichajeLocalService getFichajeLocalService() {
		return fichajeLocalService;
	}

	/**
	 * Sets the fichaje local service.
	 *
	 * @param fichajeLocalService the fichaje local service
	 */
	public void setFichajeLocalService(FichajeLocalService fichajeLocalService) {
		this.fichajeLocalService = fichajeLocalService;
	}

	/**
	 * Returns the fichaje persistence.
	 *
	 * @return the fichaje persistence
	 */
	public FichajePersistence getFichajePersistence() {
		return fichajePersistence;
	}

	/**
	 * Sets the fichaje persistence.
	 *
	 * @param fichajePersistence the fichaje persistence
	 */
	public void setFichajePersistence(FichajePersistence fichajePersistence) {
		this.fichajePersistence = fichajePersistence;
	}

	/**
	 * Returns the servicio local service.
	 *
	 * @return the servicio local service
	 */
	public es.vass.fichaje.service.ServicioLocalService getServicioLocalService() {
		return servicioLocalService;
	}

	/**
	 * Sets the servicio local service.
	 *
	 * @param servicioLocalService the servicio local service
	 */
	public void setServicioLocalService(
		es.vass.fichaje.service.ServicioLocalService servicioLocalService) {
		this.servicioLocalService = servicioLocalService;
	}

	/**
	 * Returns the servicio persistence.
	 *
	 * @return the servicio persistence
	 */
	public ServicioPersistence getServicioPersistence() {
		return servicioPersistence;
	}

	/**
	 * Sets the servicio persistence.
	 *
	 * @param servicioPersistence the servicio persistence
	 */
	public void setServicioPersistence(ServicioPersistence servicioPersistence) {
		this.servicioPersistence = servicioPersistence;
	}

	/**
	 * Returns the tipo servicio local service.
	 *
	 * @return the tipo servicio local service
	 */
	public es.vass.fichaje.service.TipoServicioLocalService getTipoServicioLocalService() {
		return tipoServicioLocalService;
	}

	/**
	 * Sets the tipo servicio local service.
	 *
	 * @param tipoServicioLocalService the tipo servicio local service
	 */
	public void setTipoServicioLocalService(
		es.vass.fichaje.service.TipoServicioLocalService tipoServicioLocalService) {
		this.tipoServicioLocalService = tipoServicioLocalService;
	}

	/**
	 * Returns the tipo servicio persistence.
	 *
	 * @return the tipo servicio persistence
	 */
	public TipoServicioPersistence getTipoServicioPersistence() {
		return tipoServicioPersistence;
	}

	/**
	 * Sets the tipo servicio persistence.
	 *
	 * @param tipoServicioPersistence the tipo servicio persistence
	 */
	public void setTipoServicioPersistence(
		TipoServicioPersistence tipoServicioPersistence) {
		this.tipoServicioPersistence = tipoServicioPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Returns the asset entry local service.
	 *
	 * @return the asset entry local service
	 */
	public com.liferay.asset.kernel.service.AssetEntryLocalService getAssetEntryLocalService() {
		return assetEntryLocalService;
	}

	/**
	 * Sets the asset entry local service.
	 *
	 * @param assetEntryLocalService the asset entry local service
	 */
	public void setAssetEntryLocalService(
		com.liferay.asset.kernel.service.AssetEntryLocalService assetEntryLocalService) {
		this.assetEntryLocalService = assetEntryLocalService;
	}

	/**
	 * Returns the asset entry persistence.
	 *
	 * @return the asset entry persistence
	 */
	public AssetEntryPersistence getAssetEntryPersistence() {
		return assetEntryPersistence;
	}

	/**
	 * Sets the asset entry persistence.
	 *
	 * @param assetEntryPersistence the asset entry persistence
	 */
	public void setAssetEntryPersistence(
		AssetEntryPersistence assetEntryPersistence) {
		this.assetEntryPersistence = assetEntryPersistence;
	}

	/**
	 * Returns the asset tag local service.
	 *
	 * @return the asset tag local service
	 */
	public com.liferay.asset.kernel.service.AssetTagLocalService getAssetTagLocalService() {
		return assetTagLocalService;
	}

	/**
	 * Sets the asset tag local service.
	 *
	 * @param assetTagLocalService the asset tag local service
	 */
	public void setAssetTagLocalService(
		com.liferay.asset.kernel.service.AssetTagLocalService assetTagLocalService) {
		this.assetTagLocalService = assetTagLocalService;
	}

	/**
	 * Returns the asset tag persistence.
	 *
	 * @return the asset tag persistence
	 */
	public AssetTagPersistence getAssetTagPersistence() {
		return assetTagPersistence;
	}

	/**
	 * Sets the asset tag persistence.
	 *
	 * @param assetTagPersistence the asset tag persistence
	 */
	public void setAssetTagPersistence(AssetTagPersistence assetTagPersistence) {
		this.assetTagPersistence = assetTagPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("es.vass.fichaje.model.Fichaje",
			fichajeLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"es.vass.fichaje.model.Fichaje");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return FichajeLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Fichaje.class;
	}

	protected String getModelClassName() {
		return Fichaje.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = fichajePersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = FichajeLocalService.class)
	protected FichajeLocalService fichajeLocalService;
	@BeanReference(type = FichajePersistence.class)
	protected FichajePersistence fichajePersistence;
	@BeanReference(type = es.vass.fichaje.service.ServicioLocalService.class)
	protected es.vass.fichaje.service.ServicioLocalService servicioLocalService;
	@BeanReference(type = ServicioPersistence.class)
	protected ServicioPersistence servicioPersistence;
	@BeanReference(type = es.vass.fichaje.service.TipoServicioLocalService.class)
	protected es.vass.fichaje.service.TipoServicioLocalService tipoServicioLocalService;
	@BeanReference(type = TipoServicioPersistence.class)
	protected TipoServicioPersistence tipoServicioPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = com.liferay.asset.kernel.service.AssetEntryLocalService.class)
	protected com.liferay.asset.kernel.service.AssetEntryLocalService assetEntryLocalService;
	@ServiceReference(type = AssetEntryPersistence.class)
	protected AssetEntryPersistence assetEntryPersistence;
	@ServiceReference(type = com.liferay.asset.kernel.service.AssetTagLocalService.class)
	protected com.liferay.asset.kernel.service.AssetTagLocalService assetTagLocalService;
	@ServiceReference(type = AssetTagPersistence.class)
	protected AssetTagPersistence assetTagPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}