/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.fichaje.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Servicio service. Represents a row in the &quot;Fichaje_Servicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.vass.fichaje.model.impl.ServicioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.vass.fichaje.model.impl.ServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Servicio
 * @see es.vass.fichaje.model.impl.ServicioImpl
 * @see es.vass.fichaje.model.impl.ServicioModelImpl
 * @generated
 */
@ProviderType
public interface ServicioModel extends BaseModel<Servicio> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a servicio model instance should use the {@link Servicio} interface instead.
	 */

	/**
	 * Returns the primary key of this servicio.
	 *
	 * @return the primary key of this servicio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this servicio.
	 *
	 * @param primaryKey the primary key of this servicio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id servicio of this servicio.
	 *
	 * @return the id servicio of this servicio
	 */
	public long getIdServicio();

	/**
	 * Sets the id servicio of this servicio.
	 *
	 * @param idServicio the id servicio of this servicio
	 */
	public void setIdServicio(long idServicio);

	/**
	 * Returns the activo of this servicio.
	 *
	 * @return the activo of this servicio
	 */
	public boolean getActivo();

	/**
	 * Returns <code>true</code> if this servicio is activo.
	 *
	 * @return <code>true</code> if this servicio is activo; <code>false</code> otherwise
	 */
	public boolean isActivo();

	/**
	 * Sets whether this servicio is activo.
	 *
	 * @param activo the activo of this servicio
	 */
	public void setActivo(boolean activo);

	/**
	 * Returns the hora inicio of this servicio.
	 *
	 * @return the hora inicio of this servicio
	 */
	public Date getHoraInicio();

	/**
	 * Sets the hora inicio of this servicio.
	 *
	 * @param horaInicio the hora inicio of this servicio
	 */
	public void setHoraInicio(Date horaInicio);

	/**
	 * Returns the hora fin of this servicio.
	 *
	 * @return the hora fin of this servicio
	 */
	public Date getHoraFin();

	/**
	 * Sets the hora fin of this servicio.
	 *
	 * @param horaFin the hora fin of this servicio
	 */
	public void setHoraFin(Date horaFin);

	/**
	 * Returns the duracion of this servicio.
	 *
	 * @return the duracion of this servicio
	 */
	public double getDuracion();

	/**
	 * Sets the duracion of this servicio.
	 *
	 * @param duracion the duracion of this servicio
	 */
	public void setDuracion(double duracion);

	/**
	 * Returns the longitud of this servicio.
	 *
	 * @return the longitud of this servicio
	 */
	public double getLongitud();

	/**
	 * Sets the longitud of this servicio.
	 *
	 * @param longitud the longitud of this servicio
	 */
	public void setLongitud(double longitud);

	/**
	 * Returns the latitud of this servicio.
	 *
	 * @return the latitud of this servicio
	 */
	public double getLatitud();

	/**
	 * Sets the latitud of this servicio.
	 *
	 * @param latitud the latitud of this servicio
	 */
	public void setLatitud(double latitud);

	/**
	 * Returns the id tipo servicio of this servicio.
	 *
	 * @return the id tipo servicio of this servicio
	 */
	public long getIdTipoServicio();

	/**
	 * Sets the id tipo servicio of this servicio.
	 *
	 * @param idTipoServicio the id tipo servicio of this servicio
	 */
	public void setIdTipoServicio(long idTipoServicio);

	/**
	 * Returns the fichaje ID of this servicio.
	 *
	 * @return the fichaje ID of this servicio
	 */
	public long getFichajeId();

	/**
	 * Sets the fichaje ID of this servicio.
	 *
	 * @param fichajeId the fichaje ID of this servicio
	 */
	public void setFichajeId(long fichajeId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Servicio servicio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Servicio> toCacheModel();

	@Override
	public Servicio toEscapedModel();

	@Override
	public Servicio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}